### ISSUE TITLE
duplicate for txrequests

### ISSUE THREAD

**Issue by tardyp** [sametmax/requests-twisted#2]
Hi,
txrequests is a port of requests-future for twisted.
It is used has been created and has been used by buildbot people for > 1 year, is very stable and maintained

tx is a common prefix for libraries made for twisted, and not originally supported by the twisted team.

I don't think there is a need for competition in the not so crowded twisted community, so can you please update your pypi repository, and rather point to txrequests?

**Comment by sametmax** [comment]
I'm ok with that.

**Comment by sametmax** [comment]
Done.

**Comment by tardyp** [comment]
thanks, apreciated
